general:
  project_name: test_project
  camera_type: FLIR
  camera_model: BFS-U3-200S6C-C
camera_settings:
  exposure_auto: false
  exposure_time: 90000.0
  gain_auto: false
  gain_level: 1.83
  gamma: 0.8
  balance_ratio_red: 1.58
  balance_ratio_blue: 1.79
  shutterspeed: ''
  aperture: ''
  iso: ''
  whitebalance: ''
  compression: ''
scanner_settings:
  x_min: 0.0
  x_max: 450.0
  x_step: 50.0
  y_min: 0.0
  y_max: 1600.0
  y_step: 80.0
  z_min: -20000.0
  z_max: -8000.0
  z_step: 500.0
stacking:
  stack_images: false
  stacking_method: default
  threshold: 10
  display_focus_check: false
  additional_sharpening: false
masking:
  mask_images: false
  mask_thresh_min: 175
  mask_thresh_max: 215
  min_artifact_size_black: 1000
  min_artifact_size_white: 2000
exif_data:
  Make: FLIR
  Model: BFS-U3-200S6C-C
  SerialNumber: '20531153'
  Lens: MPZ
  CameraSerialNumber: '20531153'
  LensManufacturer: Computar
  LensModel: 35.0 f / 2.2
  FocalLength: '35.0'
  FocalLengthIn35mmFormat: '95.0'
